version: '3.7'

services:
  space_db_api:
    container_name: space_db_api
    image: space/db/api
    build:
      context: .
      dockerfile: SpaceDb/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "444:443"
      - "20101:8080"
networks:
  private-network:
    name: spacedb_network
    external: true
