version: '3.7'

services:
  space_db:
    container_name: space_db
    image: postgres
    ports:
      - 54321:5432:5432
    networks:
      - private-network
    environment:
      POSTGRES_USER: 'pguser'
      POSTGRES_PASSWORD: 'pguserpass'
      POSTGRES_DB: 'space_db'

volumes:
  pgdata:
    name: space_db

networks:
  private-network:
    external:
      name: spacedb_network
